### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ChosenDango** [MillenniumEarl/F95API#299]
**Describe the bug**
When I npm run the example I get the error show in the screenshot

**To Reproduce**
1. Go to 'termina'
2. Run on 'npm run example'
3. See error

**Expected behavior**
For the example to work.

**Screenshots**
![image](https://github.com/MillenniumEarl/F95API/assets/79312289/f78d6139-622c-4ae9-b348-a05aaed2e8de)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: 1.51.114

**Comment by MillenniumEarl** [comment]
Hi!

I was convinced that I had already closed the issue but apparently I must have dreamed it.

The problem was due to the version of the inquirer dependency, since it is only used in development and only for examples, I reverted to the previous version, now it should work correctly.

I will release the package on npm as soon as possible
